[package]
name = "lyra"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
lofty = "0.22.4"
mpd = "*"
serde = { version = "1.0.219", features = ["derive"] }
tempfile = "3.20.0"
toml = "0.9.2"
